print("Old MacDonald had a farm, E-I-E-I-O")
print("And on his farm he had a pig, E-I-E-I-O")
print("With an Oink Oink here, and an Oink Oink there")
print("Here an Oink, there an Oink, everywhere an Oink Oink")
print("Old MacDonald had a farm, E-I-E-I-O")

print("Old MacDonald had a farm, E-I-E-I-O")
print("And on his farm he had a cow, E-I-E-I-O")
print("With a Moo Moo here, and a Moo Moo there")
print("Here a Moo, there a Moo, everywhere a Moo Moo")
print("Old MacDonald had a farm, E-I-E-I-O")
